class pawnMap():
    """
    General values given to black's pawns based on where they are on the board.
    """
    def __init__(self, square: str) -> None:
        self.square = square

    def mapValue(self) -> int:
        """
        returns the value from where the pawn is.
        """
        map = {
            'a1': 0,
            'b1': 0,
            'c1': 0,
            'd1': 0,
            'e1': 0,
            'f1': 0,
            'g1': 0,
            'h1': 0,
            'a2': -5.0,
            'b2': -5.0,
            'c2': -5.0,
            'd2': -5.0,
            'e2': -5.0,
            'f2': -5.0,
            'g2': -5.0,
            'h2': -5.0,
            'a3': -1.0,
            'b3': -1.0,
            'c3': -2.0,
            'd3': -3.0,
            'e3': -3.0,
            'f3': -2.0,
            'g3': -1.0,
            'h3': -1.0,
            'a4': -0.5,
            'b4': -0.5,
            'c4': -1.0,
            'd4': -2.5,
            'e4': -2.5,
            'f4': -1.0,
            'g4': -0.5,
            'h4': -0.5,
            'a5': 0,
            'b5': 0,
            'c5': 0,
            'd5': -2.0,
            'e5': -2.0,
            'f5': 0,
            'g5': 0,
            'h5': 0,
            'a6': -0.6,
            'b6': 0.5,
            'c6': 1.0,
            'd6': 0,
            'e6': 0,
            'f6': 1.0,
            'g6': 0.5,
            'h6': -0.5,
            'a7': -0.5,
            'b7': -1.0,
            'c7': -1.0,
            'd7': 2.0,
            'e7': 2.0,
            'f7': -1.0,
            'g7': -1.0,
            'h7': -0.5,
            'a8': 0,
            'b8': 0,
            'c8': 0,
            'd8': 0,
            'e8': 0,
            'f8': 0,
            'g8': 0,
            'h8': 0,
        }
        return map[self.square]

class knightMap():
    """
    general values given to black's knights based on where they are on the board.
    """
    def __init__(self, square: str) -> None:
        self.square = square

    def mapValue(self) -> int:
        """
        returns the value from where the knight is.
        """
        map = {
            'a1': 5.0,
            'b1': 4.0,
            'c1': 3.0,
            'd1': 3.0,
            'e1': 3.0,
            'f1': 3.0,
            'g1': 4.0,
            'h1': 5.0,
            'a2': 4.0,
            'b2': 2.0,
            'c2': 0,
            'd2': 0,
            'e2': 0,
            'f2': 0,
            'g2': 2.0,
            'h2': 4.0,
            'a3': 3.0,
            'b3': 0,
            'c3': -1.0,
            'd3': -1.5,
            'e3': -1.5,
            'f3': -1.0,
            'g3': 0,
            'h3': 3.0,
            'a4': 3.0,
            'b4': -0.5,
            'c4': -1.5,
            'd4': -2.0,
            'e4': -2.0,
            'f4': -1.5,
            'g4': -0.5,
            'h4': 3.0,
            'a5': 3.0,
            'b5': 0,
            'c5': -1.5,
            'd5': -2.0,
            'e5': -2.0,
            'f5': -1.5,
            'g5': 0,
            'h5': 3.0,
            'a6': 3.0,
            'b6': -0.5,
            'c6': -1.0,
            'd6': -1.5,
            'e6': -1.5,
            'f6': -1.0,
            'g6': -0.5,
            'h6': 3.0,
            'a7': 4.0,
            'b7': 2.0,
            'c7': 0,
            'd7': -0.5,
            'e7': -0.5,
            'f7': 0,
            'g7': 2.0,
            'h7': 4.0,
            'a8': 5.0,
            'b8': 4.0,
            'c8': 3.0,
            'd8': 3.0,
            'e8': 3.0,
            'f8': 3.0,
            'g8': 4.0,
            'h8': 5.0,
        }
        return map[self.square]
    
class bishopMap():
    """
    general values given to black's bishops based on where they are on the board.
    """
    def __init__(self, square: str) -> None:
        self.square = square

    def mapValue(self) -> int:
        """
        returns the value from where the bishop is.
        """
        map = {
            'a1': 2.0,
            'b1': 1.0,
            'c1': 1.0,
            'd1': 1.0,
            'e1': 1.0,
            'f1': 1.0,
            'g1': 1.0,
            'h1': 2.0,
            'a2': 1.0,
            'b2': 0,
            'c2': 0,
            'd2': 0,
            'e2': 0,
            'f2': 0,
            'g2': 0,
            'h2': 1.0,
            'a3': 1.0,
            'b3': 0,
            'c3': -0.5,
            'd3': -1.0,
            'e3': -1.0,
            'f3': -0.5,
            'g3': 0,
            'h3': 1.0,
            'a4': 1.0,
            'b4': -0.5,
            'c4': -0.5,
            'd4': -1.0,
            'e4': -1.0,
            'f4': -0.5,
            'g4': -0.5,
            'h4': 1.0,
            'a5': 1.0,
            'b5': 0,
            'c5': -1.0,
            'd5': -1.0,
            'e5': -1.0,
            'f5': -1.0,
            'g5': 0,
            'h5': 1.0,
            'a6': 1.0,
            'b6': -1.0,
            'c6': -1.0,
            'd6': -1.0,
            'e6': -1.0,
            'f6': -1.0,
            'g6': -1.0,
            'h6': 1.0,
            'a7': 1.0,
            'b7': -0.5,
            'c7': 0,
            'd7': 0,
            'e7': 0,
            'f7': 0,
            'g7': -0.5,
            'h7': 1.0,
            'a8': 2.0,
            'b8': 1.0,
            'c8': 1.0,
            'd8': 1.0,
            'e8': 1.0,
            'f8': 1.0,
            'g8': 1.0,
            'h8': 2.0,
        }
        return map[self.square]

class rookMap():
    """
    general values given to black's rooks based on where they are on the board.
    """
    def __init__(self, square: str) -> None:
        self.square = square

    def mapValue(self) -> int:
        """
        returns the value from where the rook is.
        """
        map = {
            'a1': 0,
            'b1': 0,
            'c1': 0,
            'd1': 0,
            'e1': 0,
            'f1': 0,
            'g1': 0,
            'h1': 0,
            'a2': -0.5,
            'b2': -1.0,
            'c2': -1.0,
            'd2': -1.0,
            'e2': -1.0,
            'f2': -1.0,
            'g2': -1.0,
            'h2': -0.5,
            'a3': 0.5,
            'b3': 0,
            'c3': 0,
            'd3': 0,
            'e3': 0,
            'f3': 0,
            'g3': 0,
            'h3': 0.5,
            'a4': 0.5,
            'b4': 0,
            'c4': 0,
            'd4': 0,
            'e4': 0,
            'f4': 0,
            'g4': 0,
            'h4': 0.5,
            'a5': 0.5,
            'b5': 0,
            'c5': 0,
            'd5': 0,
            'e5': 0,
            'f5': 0,
            'g5': 0,
            'h5': 0.5,
            'a6': 0.5,
            'b6': 0,
            'c6': 0,
            'd6': 0,
            'e6': 0,
            'f6': 0,
            'g6': 0,
            'h6': 0.5,
            'a7': 0.5,
            'b7': 0,
            'c7': 0,
            'd7': 0,
            'e7': 0,
            'f7': 0,
            'g7': 0,
            'h7': 0.5,
            'a8': 0,
            'b8': 0,
            'c8': 0,
            'd8': -0.5,
            'e8': -0.5,
            'f8': 0,
            'g8': 0,
            'h8': 0,
        }
        return map[self.square]

class queenMap():
    """
    general value given to black's queen based on where she is on the board.
    """
    def __init__(self, square: str) -> None:
        self.square = square

    def mapValue(self) -> int:
        """
        returns the value from where the queen is.
        """
        map = {
            'a1': 2.0,
            'b1': 1.0,
            'c1': 1.0,
            'd1': 0.5,
            'e1': 0.5,
            'f1': 1.0,
            'g1': 1.0,
            'h1': 2.0,
            'a2': 1.0,
            'b2': 0,
            'c2': 0,
            'd2': 0,
            'e2': 0,
            'f2': 0,
            'g2': 0,
            'h2': 1.0,
            'a3': 1.0,
            'b3': 0,
            'c3': -0.5,
            'd3': -0.5,
            'e3': -0.5,
            'f3': -0.5,
            'g3': 0,
            'h3': 1.0,
            'a4': 0.5,
            'b4': 0,
            'c4': -0.5,
            'd4': -0.5,
            'e4': -0.5,
            'f4': -0.5,
            'g4': 0,
            'h4': 0.5,
            'a5': 0,
            'b5': 0,
            'c5': -0.5,
            'd5': -0.5,
            'e5': -0.5,
            'f5': -0.5,
            'g5': 0,
            'h5': 0.5,
            'a6': 1.0,
            'b6': -0.5,
            'c6': -0.5,
            'd6': -0.5,
            'e6': -0.5,
            'f6': -0.5,
            'g6': 0,
            'h6': 1.0,
            'a7': 1.0,
            'b7': 0,
            'c7': -0.5,
            'd7': 0,
            'e7': 0,
            'f7': 0,
            'g7': 0,
            'h7': 1.0,
            'a8': 2.0,
            'b8': 1.0,
            'c8': 1.0,
            'd8': 0.5,
            'e8': 0.5,
            'f8': 1.0,
            'g8': 1.0,
            'h8': 2.0,
        }
        return map[self.square]

class earlyKingMap():
    """
    general value given to black's king based on where he is on the board.
    """
    def __init__(self, square: str) -> None:
        self.square = square

    def mapValue(self) -> int:
        """
        returns the value from where the king is.
        """
        map = {
            'a1': 3.0,
            'b1': 4.0,
            'c1': 4.0,
            'd1': 5.0,
            'e1': 5.0,
            'f1': 4.0,
            'g1': 4.0,
            'h1': 3.0,
            'a2': 3.0,
            'b2': 4.0,
            'c2': 4.0,
            'd2': 5.0,
            'e2': 5.0,
            'f2': 4.0,
            'g2': 4.0,
            'h2': 3.0,
            'a3': 3.0,
            'b3': 4.0,
            'c3': 4.0,
            'd3': 5.0,
            'e3': 5.0,
            'f3': 4.0,
            'g3': 4.0,
            'h3': 3.0,
            'a4': 3.0,
            'b4': 4.0,
            'c4': 4.0,
            'd4': 5.0,
            'e4': 5.0,
            'f4': 4.0,
            'g4': 4.0,
            'h4': 3.0,
            'a5': 2.0,
            'b5': 3.0,
            'c5': 3.0,
            'd5': 4.0,
            'e5': 4.0,
            'f5': 3.0,
            'g5': 3.0,
            'h5': 2.0,
            'a6': 1.0,
            'b6': 2.0,
            'c6': 2.0,
            'd6': 2.0,
            'e6': 2.0,
            'f6': 2.0,
            'g6': 2.0,
            'h6': 1.0,
            'a7': -2.0,
            'b7': -2.0,
            'c7': 0,
            'd7': 0,
            'e7': 0,
            'f7': 0,
            'g7': -2.0,
            'h7': -2.0,
            'a8': -2.0,
            'b8': -3.0,
            'c8': -1.0,
            'd8': 0,
            'e8': 0,
            'f8': -1.0,
            'g8': -3.0,
            'h8': -2.0,
        }
        return map[self.square]
